---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lotus-gateway
  labels:
    app: lotus-gateway-app
{{- with .Values.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: lotus-gateway-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: lotus-gateway-app
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
{{- with .Values.additionalLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      securityContext:
        fsGroup: 532
        runAsNonRoot: true
        runAsUser: 532
        runAsGroup: 532
      containers:
      - name: gateway
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/lotus-gateway", "run"]
        {{- with .Values.runArgs }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        {{- with .Values.gatewayEnvs }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.secrets.jwt.enabled }}
          - name: LOTUS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.jwt.secretName }}
                key: {{ .Values.secrets.jwt.token_key }}
          - name: FULLNODE_API_INFO
            value: "$(LOTUS_API_TOKEN):{{ .Values.lotus.fullnodeApiMultiaddr }}"
        {{- else }}
          - name: FULLNODE_API_INFO
            value: "{{ .Values.lotus.fullnodeApiMultiaddr }}"
        {{- end }}
