apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tweety-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-tweety-daemon
spec:
  ports:
  - port: 1337
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-tweety-daemon
