apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel-tick.fullname" . }}
  labels:
    app: sentinel-tick
    suite: sentinel
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sentinel-tick
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: sentinel-tick
        suite: sentinel
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: ""
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 2111
              name: metrics

          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: user
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: database
            - name: SENTINEL_TICK_DB
              value: "postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST):$(PGPORT)/$(PGDATABASE)?sslmode={{ .Values.pgSSLMode }}"
            - name: SENTINEL_TICK_POOL_SIZE
              value: "{{ .Values.pgPoolSize }}"
            - name: SENTINEL_TICK_METRICS
              value: "0.0.0.0:2111"
            - name: SENTINEL_TICK_PAIRS
              value: "{{ .Values.pairs }}"
            - name: SENTINEL_TICK_COINMARKETCAP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ required "required field exchangeSecrets is empty" .Values.exchangeSecrets }}"
                  key: coinmarketcap
            - name: SENTINEL_TICK_COINMARKETCAP
              value: "{{ .Values.exchanges.coinmarketcap }}"


          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
