{{- if .Values.prometheusOperatorServiceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-sentinel-tick
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: sentinel-tick
      release: {{ .Release.Name }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
{{- end }}
