apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentinel-tick
  labels:
    app: sentinel-tick
    release: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2111"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
      app: sentinel-tick
      release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 2111
      targetPort: 2111
      name: metrics
