---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lotus-stats.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lotus-stats.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lotus-stats.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 6688
      targetPort: 6688
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lotus-stats.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lotus-stats.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "lotus-stats.labels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lotus-stats.fullname" . }}
  labels:
    {{- include "lotus-stats.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lotus-stats.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lotus-stats.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: stats
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/lotus-stats", "run"]
        args:
          - -no-sync={{ .Values.nosync }}
          - -head-lag={{ .Values.headlag }}
          - -height={{ .Values.height }}
        env:
          - name: FULLNODE_API_INFO
            value: {{ .Values.lotusApiInfo }}
          - name: LOTUS_STATS_INFLUX_DATABASE
            value: {{ .Values.influxDatabase }}
          - name: LOTUS_STATS_INFLUX_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxSecrets }}
                key: influx_hostname
          - name: LOTUS_STATS_INFLUX_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxSecrets }}
                key: influx_username
          - name: LOTUS_STATS_INFLUX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxSecrets }}
                key: influx_password
        ports:
        - containerPort: 6688
          name: metrics
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 4 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 4 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 4 }}
      {{- end }}
