{{- range $cm := .Values.application.configMaps }}
{{- if not $cm.external }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $cm.name }}
data:
  {{- range $k, $v := .keys }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}

{{- range $cm := .Values.filebeat.configMaps }}
{{- if not $cm.external }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $cm.name }}
data:
  {{- range $k, $v := .keys }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
