{{- range $sec := .Values.application.secrets }}
{{- if not $sec.external }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $sec.name }}
data:
  {{- range $k, $v := .keys }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- if and .Values.filebeat.enabled }}
{{- range $sec := .Values.filebeat.secrets }}
{{- if not $sec.external }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $sec.name }}
data:
  {{- range $k, $v := .keys }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
